// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/lczm/kilter-together",
            "email": "opensource@lczm.me"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/boards": {
            "get": {
                "description": "Retrieve all available board/product size options for filtering climbs. Returns a list of board configurations with their IDs and human-readable names.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Get available board options",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved board options",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.BoardOption"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/climbs": {
            "get": {
                "description": "Retrieve a paginated list of listed Kilter Board climbs with filtering, sorting, and cursor-based pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "climbs"
                ],
                "summary": "Get paginated climbs",
                "parameters": [
                    {
                        "type": "string",
                        "example": "eyJzb3J0IjoicG9wdWxhciIsImFzY2VuZHMiOjQyLCJjcmVhdGVkX2F0IjoiMjAyNi0wMS0wMSAwMDowMDowMC4wMDAwMDAiLCJ1dWlkIjoidXVpZC0xIiwicHJvZHVjdF9zaXplX2lkIjoxNH0=",
                        "description": "Pagination cursor returned by the previous page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "Number of items per page (1-100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "swooped",
                        "description": "Filter climbs by climb name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "jwebxl",
                        "description": "Filter climbs by setter username (partial match)",
                        "name": "setter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 14,
                        "description": "Filter climbs by board/product size ID",
                        "name": "board_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 40,
                        "description": "Filter climbs by board angle (supported angles: 5-70)",
                        "name": "angle",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "popular",
                            "newest"
                        ],
                        "type": "string",
                        "default": "popular",
                        "description": "Sort order for the result set",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved climbs",
                        "schema": {
                            "$ref": "#/definitions/models.CursorPaginatedClimbsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/images/{filename}": {
            "get": {
                "description": "Serve static image files for board layouts and holds. Images are used to display the physical board layout with hold positions for each climb.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/png",
                    "image/jpeg",
                    "image/gif"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Serve board layout images",
                "parameters": [
                    {
                        "type": "string",
                        "example": "original-16x12-bolt-ons-v2.png",
                        "description": "Image filename",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully served image file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid filename",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found - image file does not exist",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms": {
            "post": {
                "description": "Create a room, validate the provider secret, persist the host session, and return the initial room snapshot.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Create a collaborative room",
                "parameters": [
                    {
                        "description": "Create room payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rooms.RoomSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}": {
            "get": {
                "description": "Return the current collaborative room snapshot for the authenticated viewer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Get a room snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rooms.RoomSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update the room name for the host-managed collaborative room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Update room metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Room update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rooms.RoomSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/catalog/climbs": {
            "get": {
                "description": "Return provider climbs for the room surface along with room vote metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "List room catalog climbs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rooms.CatalogClimbsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/catalog/climbs/{climbId}": {
            "get": {
                "description": "Return a single provider climb for the room surface along with room vote metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Get a room catalog climb",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Provider climb id",
                        "name": "climbId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rooms.CatalogClimbResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/catalog/surfaces": {
            "get": {
                "description": "Return provider-specific selectable surfaces for the room, optionally filtered by parent id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "List provider surfaces for the room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent surface id",
                        "name": "parent_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.listSurfacesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/fist-bumps/settings": {
            "put": {
                "description": "Enable or disable room fist bumps for the host-managed collaborative room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Update room fist bump settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fist bump settings payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateFistBumpsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rooms.RoomSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/join": {
            "post": {
                "description": "Create a participant session for the room and return the room snapshot for the joining guest.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Join an existing room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Join room payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.joinRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rooms.RoomSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/pick-random": {
            "post": {
                "description": "Pick a random climb from finalists or top-voted climbs for the room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Pick a random room climb",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Random pick payload",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.pickRandomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.randomPickResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/provider/connect": {
            "post": {
                "description": "Validate and persist provider credentials for the host-managed collaborative room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Connect or refresh a room provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Provider connect payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.connectProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/providers.ProviderConnectionState"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{slug}/surface": {
            "post": {
                "description": "Persist the provider-specific board, gym, or wall selection for the room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Select the shared room surface",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Surface selection payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.setSurfaceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/providers.ProviderSurface"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.connectProviderRequest": {
            "type": "object",
            "properties": {
                "secret": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.createRoomRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "room_name": {
                    "type": "string"
                },
                "secret": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.joinRoomRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                }
            }
        },
        "handlers.listSurfacesResponse": {
            "type": "object",
            "properties": {
                "surfaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/providers.ProviderSurface"
                    }
                }
            }
        },
        "handlers.pickRandomRequest": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                }
            }
        },
        "handlers.randomPickResponse": {
            "type": "object",
            "properties": {
                "climb": {
                    "$ref": "#/definitions/providers.ProviderClimb"
                }
            }
        },
        "handlers.setSurfaceRequest": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "surface_id": {
                    "type": "string"
                }
            }
        },
        "handlers.updateFistBumpsRequest": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "handlers.updateRoomRequest": {
            "type": "object",
            "properties": {
                "room_name": {
                    "type": "string"
                }
            }
        },
        "models.BoardOption": {
            "type": "object",
            "properties": {
                "climb_count": {
                    "type": "integer",
                    "example": 12453
                },
                "id": {
                    "type": "integer",
                    "example": 14
                },
                "kilter_name": {
                    "type": "string",
                    "example": "Kilter Board Original"
                },
                "name": {
                    "type": "string",
                    "example": "7 x 10"
                },
                "preview_image_filename": {
                    "type": "string",
                    "example": "product_sizes_layouts_sets/original-16x12-bolt-ons-v2.png"
                }
            }
        },
        "models.Climb": {
            "type": "object",
            "properties": {
                "ascends": {
                    "type": "integer",
                    "example": 42
                },
                "climb_name": {
                    "type": "string",
                    "example": "swooped"
                },
                "created_at": {
                    "type": "string",
                    "example": "2018-12-06 21:15:01.127371"
                },
                "description": {
                    "type": "string",
                    "example": "A challenging overhang problem"
                },
                "frames": {
                    "type": "string",
                    "example": "p1080r15p1110r15p1131r12"
                },
                "grades": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.GradeInfo"
                    }
                },
                "highlighted_holds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HighlightedHold"
                    }
                },
                "image_filenames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product_size_id": {
                    "type": "integer",
                    "example": 14
                },
                "setter_name": {
                    "type": "string",
                    "example": "jwebxl"
                },
                "uuid": {
                    "type": "string",
                    "example": "F01419E12672459396CA62E3655ABC46"
                }
            }
        },
        "models.CursorPaginatedClimbsResponse": {
            "type": "object",
            "properties": {
                "climbs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Climb"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "string",
                    "example": "eyJzb3J0IjoicG9wdWxhciIsImFzY2VuZHMiOjQyLCJjcmVhdGVkX2F0IjoiMjAyNi0wMS0wMSAwMDowMDowMC4wMDAwMDAiLCJ1dWlkIjoidXVpZC0xIiwicHJvZHVjdF9zaXplX2lkIjoxNH0="
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.GradeInfo": {
            "type": "object",
            "properties": {
                "boulder": {
                    "type": "string",
                    "example": "7a/V6"
                },
                "route": {
                    "type": "string",
                    "example": "7c/5.12d"
                }
            }
        },
        "models.HighlightedHold": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#00DD00"
                },
                "position": {
                    "type": "integer",
                    "example": 1096
                },
                "role": {
                    "type": "string",
                    "example": "start"
                },
                "x": {
                    "type": "number",
                    "example": 77.3
                },
                "y": {
                    "type": "number",
                    "example": 42.1
                }
            }
        },
        "providers.ClimbMedia": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "providers.HighlightedHold": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "providers.ProviderClimb": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "external_id": {
                    "type": "string"
                },
                "highlighted_holds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/providers.HighlightedHold"
                    }
                },
                "id": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/providers.ClimbMedia"
                    }
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "popularity": {
                    "type": "integer"
                },
                "primary_grade": {
                    "type": "string"
                },
                "provider_id": {
                    "$ref": "#/definitions/providers.ProviderID"
                },
                "secondary_grade": {
                    "type": "string"
                },
                "setter_name": {
                    "type": "string"
                },
                "surface_id": {
                    "type": "string"
                }
            }
        },
        "providers.ProviderConnectionState": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "provider_id": {
                    "$ref": "#/definitions/providers.ProviderID"
                }
            }
        },
        "providers.ProviderID": {
            "type": "string",
            "enum": [
                "kilter",
                "crux",
                "test",
                "moonboard",
                "tension",
                "grasshopper"
            ],
            "x-enum-varnames": [
                "ProviderKilter",
                "ProviderCrux",
                "ProviderTest",
                "ProviderMoonboard",
                "ProviderTension",
                "ProviderGrasshopper"
            ]
        },
        "providers.ProviderSurface": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                }
            }
        },
        "rooms.CatalogClimbResponse": {
            "type": "object",
            "properties": {
                "climb": {
                    "$ref": "#/definitions/providers.ProviderClimb"
                },
                "is_queued": {
                    "type": "boolean"
                },
                "my_vote": {
                    "type": "boolean"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        },
        "rooms.CatalogClimbsResponse": {
            "type": "object",
            "properties": {
                "climbs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/providers.ProviderClimb"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "my_votes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "next_cursor": {
                    "type": "string"
                },
                "page_size": {
                    "type": "integer"
                },
                "vote_counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "rooms.FinalistEntryView": {
            "type": "object",
            "properties": {
                "added_by": {
                    "type": "string"
                },
                "climb": {
                    "$ref": "#/definitions/providers.ProviderClimb"
                },
                "id": {
                    "type": "integer"
                },
                "position": {
                    "type": "integer"
                }
            }
        },
        "rooms.ParticipantView": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_online": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "rooms.QueueEntryView": {
            "type": "object",
            "properties": {
                "added_by": {
                    "type": "string"
                },
                "climb": {
                    "$ref": "#/definitions/providers.ProviderClimb"
                },
                "id": {
                    "type": "integer"
                },
                "position": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "rooms.RoomSnapshot": {
            "type": "object",
            "properties": {
                "can_manage": {
                    "type": "boolean"
                },
                "connection": {
                    "$ref": "#/definitions/providers.ProviderConnectionState"
                },
                "current_climb": {
                    "$ref": "#/definitions/providers.ProviderClimb"
                },
                "display_name": {
                    "type": "string"
                },
                "finalists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rooms.FinalistEntryView"
                    }
                },
                "fist_bumps_enabled": {
                    "type": "boolean"
                },
                "my_votes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rooms.ParticipantView"
                    }
                },
                "provider_id": {
                    "$ref": "#/definitions/providers.ProviderID"
                },
                "queue": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rooms.QueueEntryView"
                    }
                },
                "room_name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "surface": {
                    "$ref": "#/definitions/providers.ProviderSurface"
                },
                "version": {
                    "type": "integer"
                },
                "vote_counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "Kilter Together API Documentation",
        "url": "https://github.com/lczm/kilter-together/blob/main/api/README.md"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Kilter Together API",
	Description:      "API for solo Kilter browsing plus collaborative room sessions with Kilter and Crux provider adapters.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
