// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/lczm/kilter-together",
            "email": "opensource@lczm.me"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/boards": {
            "get": {
                "description": "Retrieve all available board/product size options for filtering climbs. Returns a list of board configurations with their IDs and human-readable names.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Get available board options",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved board options",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.BoardOption"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/climbs": {
            "get": {
                "description": "Retrieve a paginated list of listed Kilter Board climbs with filtering, sorting, and cursor-based pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "climbs"
                ],
                "summary": "Get paginated climbs",
                "parameters": [
                    {
                        "type": "string",
                        "example": "eyJzb3J0IjoicG9wdWxhciIsImFzY2VuZHMiOjQyLCJjcmVhdGVkX2F0IjoiMjAyNi0wMS0wMSAwMDowMDowMC4wMDAwMDAiLCJ1dWlkIjoidXVpZC0xIiwicHJvZHVjdF9zaXplX2lkIjoxNH0=",
                        "description": "Pagination cursor returned by the previous page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "Number of items per page (1-100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "swooped",
                        "description": "Filter climbs by climb name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "jwebxl",
                        "description": "Filter climbs by setter username (partial match)",
                        "name": "setter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 14,
                        "description": "Filter climbs by board/product size ID",
                        "name": "board_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 40,
                        "description": "Filter climbs by board angle (supported angles: 5-70)",
                        "name": "angle",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "popular",
                            "newest"
                        ],
                        "type": "string",
                        "default": "popular",
                        "description": "Sort order for the result set",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved climbs",
                        "schema": {
                            "$ref": "#/definitions/models.CursorPaginatedClimbsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/images/{filename}": {
            "get": {
                "description": "Serve static image files for board layouts and holds. Images are used to display the physical board layout with hold positions for each climb.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/png",
                    "image/jpeg",
                    "image/gif"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Serve board layout images",
                "parameters": [
                    {
                        "type": "string",
                        "example": "original-16x12-bolt-ons-v2.png",
                        "description": "Image filename",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully served image file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid filename",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found - image file does not exist",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BoardOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 14
                },
                "kilter_name": {
                    "type": "string",
                    "example": "Kilter Board Original"
                },
                "name": {
                    "type": "string",
                    "example": "7 x 10"
                }
            }
        },
        "models.Climb": {
            "type": "object",
            "properties": {
                "ascends": {
                    "type": "integer",
                    "example": 42
                },
                "climb_name": {
                    "type": "string",
                    "example": "swooped"
                },
                "created_at": {
                    "type": "string",
                    "example": "2018-12-06 21:15:01.127371"
                },
                "description": {
                    "type": "string",
                    "example": "A challenging overhang problem"
                },
                "frames": {
                    "type": "string",
                    "example": "p1080r15p1110r15p1131r12"
                },
                "grades": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.GradeInfo"
                    }
                },
                "image_filenames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product_size_id": {
                    "type": "integer",
                    "example": 14
                },
                "setter_name": {
                    "type": "string",
                    "example": "jwebxl"
                },
                "uuid": {
                    "type": "string",
                    "example": "F01419E12672459396CA62E3655ABC46"
                }
            }
        },
        "models.CursorPaginatedClimbsResponse": {
            "type": "object",
            "properties": {
                "climbs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Climb"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "string",
                    "example": "eyJzb3J0IjoicG9wdWxhciIsImFzY2VuZHMiOjQyLCJjcmVhdGVkX2F0IjoiMjAyNi0wMS0wMSAwMDowMDowMC4wMDAwMDAiLCJ1dWlkIjoidXVpZC0xIiwicHJvZHVjdF9zaXplX2lkIjoxNH0="
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.GradeInfo": {
            "type": "object",
            "properties": {
                "boulder": {
                    "type": "string",
                    "example": "7a/V6"
                },
                "route": {
                    "type": "string",
                    "example": "7c/5.12d"
                }
            }
        }
    },
    "externalDocs": {
        "description": "Kilter Together API Documentation",
        "url": "https://github.com/lczm/kilter-together/blob/main/api/README.md"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Kilter Together API",
	Description:      "API for solo Kilter browsing plus collaborative room sessions with Kilter and Crux provider adapters.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
