#!/bin/bash

# Noupe Clean — removes all artifacts generated by train_dev.sh

ROOT="$(cd "$(dirname "$0")" && pwd)"

echo "🧹 Cleaning training artifacts..."

rm -rf "$ROOT/.train_tmp"
rm -f "$ROOT/all_embeddings.npy" "$ROOT/public_embeddings.npy" "$ROOT/violation_embeddings.npy"
rm -rf "$ROOT/layer3-clustering/checkpoints"
rm -rf "$ROOT/layer4-classification/model-1/checkpoints"
rm -rf "$ROOT/layer4-classification/model-2/checkpoints"

echo "✅ All training artifacts removed."
