services:
  alertmanager:
    command:
      - --config.file=/etc/alertmanager/generated/alertmanager.production.yml
    volumes:
      - ./observability/alertmanager/generated:/etc/alertmanager/generated:ro
