#!/bin/bash

# Noupe Clean — removes training artifacts generated by local training scripts

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKFLOW_ROOT="$ROOT/backend/workflow"

echo "🧹 Cleaning training artifacts..."

rm -rf "$ROOT/.train_tmp"
rm -f "$ROOT/all_embeddings.npy" "$ROOT/public_embeddings.npy" "$ROOT/violation_embeddings.npy"
rm -rf "$ROOT/archive/training-checkpoints"
rm -rf "$WORKFLOW_ROOT/layer3-clustering/checkpoints"
rm -rf "$WORKFLOW_ROOT/layer4-classification/model-1/checkpoints"
rm -rf "$WORKFLOW_ROOT/layer4-classification/model-2/checkpoints"

echo "✅ All training artifacts removed."
