apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: junas
  namespace: junas
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  tls:
    - hosts:
        - junas.example.com
      secretName: junas-tls
  rules:
    - host: junas.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: junas
                port:
                  name: http
